In [1]:
import numpy as np
import pandas as pd

In [2]:
# creating the test array
r=[[13, 16], [25, 36], [50, 45], [12, 34], [47, 38], [32, 3], 
   [2, 29], [40, 26], [7, 17], [17, 17], [27, 46], [23, 5] ]

In [3]:
# defining distance function
def distance(x1, y1, x2, y2):
    return np.sqrt((x1-x2)**2+(y1-y2)**2)

In [4]:
# # Creating the distance array
# dist=[[0 for i in range(len(r))]for j in range (len(r))]
# for i in range(len(r)):
#     for j in range(len(r)):
#         dist[i][j]=distance(r[i][0], r[i][1], r[j][0], r[j][1])

# # dist
# ndist=np.array(dist)
# ndist

In [5]:
# Creating the distance array
# with row 0 and col 0 contains the point's number
dist=[[i for i in range(len(r)+1)]for j in range (len(r)+1)]
for i in range(len(r)):
    dist[i+1][0]=i+1
    for j in range(len(r)):
#         dist[i+1][j+1]=7.5
        dist[i+1][j+1]=distance(r[i][0], r[i][1], r[j][0], r[j][1])

# dist
ndist=np.array(dist)
ndist

array([[  0.        ,   1.        ,   2.        ,   3.        ,
          4.        ,   5.        ,   6.        ,   7.        ,
          8.        ,   9.        ,  10.        ,  11.        ,  12.        ],
       [  1.        ,   0.        ,  23.32380758,  47.01063709,
         18.02775638,  40.49691346,  23.02172887,  17.02938637,
         28.7923601 ,   6.08276253,   4.12310563,  33.10589071,
         14.86606875],
       [  2.        ,  23.32380758,   0.        ,  26.57066051,
         13.15294644,  22.09072203,  33.73425559,  24.04163056,
         18.02775638,  26.17250466,  20.61552813,  10.19803903,
         31.06444913],
       [  3.        ,  47.01063709,  26.57066051,   0.        ,
         39.56008089,   7.61577311,  45.69463864,  50.59644256,
         21.47091055,  51.31276644,  43.27817002,  23.02172887,
         48.25971405],
       [  4.        ,  18.02775638,  13.15294644,  39.56008089,
          0.        ,  35.22782991,  36.89173349,  11.18033989,
         29.12043956

In [6]:
# Results array
res_loc = []
res_val = []

In [7]:
# a copy of ndist
ndc = ndist.copy()

In [8]:
# current row (the starting row)
rw = 1
# current array
# the slice at the end to remove the point column
curr = ndc[rw][1:]

# adding the starting point
res_loc.append(ndc[rw][0])
res_loc, res_val, curr

([1.0], [], array([  0.        ,  23.32380758,  47.01063709,  18.02775638,
         40.49691346,  23.02172887,  17.02938637,  28.7923601 ,
          6.08276253,   4.12310563,  33.10589071,  14.86606875]))

In [9]:
# find the nonzero minimum of the current array
minval = np.where( curr == np.min(curr[np.nonzero(curr)]) )
lcn, vlu  = minval[0][0], curr[minval].tolist()[0]
point_name = np.where( ndist[rw] == vlu)[0][0]
# appending the results of this stage to the results lists
res_loc.append(point_name)
res_val.append(vlu)
lcn, vlu, point_name

(9, 4.123105625617661, 10)

In [10]:
# deleting the initial row after finding the next column
ndc = np.delete(ndc, rw, axis=0)
ndc = np.delete(ndc, rw, axis=1)
ndc
ndc.shape

(12, 12)

In [11]:
ndc

array([[  0.        ,   2.        ,   3.        ,   4.        ,
          5.        ,   6.        ,   7.        ,   8.        ,
          9.        ,  10.        ,  11.        ,  12.        ],
       [  2.        ,   0.        ,  26.57066051,  13.15294644,
         22.09072203,  33.73425559,  24.04163056,  18.02775638,
         26.17250466,  20.61552813,  10.19803903,  31.06444913],
       [  3.        ,  26.57066051,   0.        ,  39.56008089,
          7.61577311,  45.69463864,  50.59644256,  21.47091055,
         51.31276644,  43.27817002,  23.02172887,  48.25971405],
       [  4.        ,  13.15294644,  39.56008089,   0.        ,
         35.22782991,  36.89173349,  11.18033989,  29.12043956,
         17.72004515,  17.72004515,  19.20937271,  31.01612484],
       [  5.        ,  22.09072203,   7.61577311,  35.22782991,
          0.        ,  38.07886553,  45.89117562,  13.89244399,
         45.17742799,  36.61966685,  21.54065923,  40.80441153],
       [  6.        ,  33.73425559,

In [12]:
# the current column
cl = lcn
# current array
# the slice at the end to remove the point column
curr = ndc[:,cl][1:]

curr

array([ 20.61552813,  43.27817002,  17.72004515,  36.61966685,
        20.51828453,  19.20937271,  24.69817807,  10.        ,
         0.        ,  30.6757233 ,  13.41640786])

In [13]:
# find the nonzero minimum of the current array
minval = np.where( curr == np.min(curr[np.nonzero(curr)]) )
lcn, vlu  = minval[0][0], curr[minval].tolist()[0]
point_name = np.where( ndist[:,cl] == vlu)[0][0]-1
# appending the results of this stage to the results lists
res_loc.append(point_name)
res_val.append(vlu)
lcn, vlu, point_name

(7, 10.0, 9)

In [14]:
# deleting the finished column
ndc = np.delete(ndc, cl, axis=1)
ndc = np.delete(ndc, cl, axis=0)
ndc
# ndc.shape

array([[  0.        ,   2.        ,   3.        ,   4.        ,
          5.        ,   6.        ,   7.        ,   8.        ,
          9.        ,  11.        ,  12.        ],
       [  2.        ,   0.        ,  26.57066051,  13.15294644,
         22.09072203,  33.73425559,  24.04163056,  18.02775638,
         26.17250466,  10.19803903,  31.06444913],
       [  3.        ,  26.57066051,   0.        ,  39.56008089,
          7.61577311,  45.69463864,  50.59644256,  21.47091055,
         51.31276644,  23.02172887,  48.25971405],
       [  4.        ,  13.15294644,  39.56008089,   0.        ,
         35.22782991,  36.89173349,  11.18033989,  29.12043956,
         17.72004515,  19.20937271,  31.01612484],
       [  5.        ,  22.09072203,   7.61577311,  35.22782991,
          0.        ,  38.07886553,  45.89117562,  13.89244399,
         45.17742799,  21.54065923,  40.80441153],
       [  6.        ,  33.73425559,  45.69463864,  36.89173349,
         38.07886553,   0.        ,  39.6

In [15]:
ndc.shape

(11, 11)

In [17]:
# Combining all above

# Preparation
# Results array
res_loc = []
res_val = []
# a copy of ndist
ndc = ndist.copy()
# current row (the starting row)
def do_one_step(rw, ndc):
        # current array
    # the slice at the end to remove the point column
    curr = ndc[rw][1:]
    # adding the starting point
    res_loc.append(ndc[rw][0])
    # res_loc, res_val, curr

    # find the nonzero minimum of the current array
    minval = np.where( curr == np.min(curr[np.nonzero(curr)]) )
    lcn, vlu  = minval[0][0], curr[minval].tolist()[0]
    point_name = np.where( ndist[rw] == vlu)[0][0]
    print(rw, lcn, vlu, point_name)
    # appending the results of this stage to the results lists
    res_loc.append(point_name)
    res_val.append(vlu)
    # lcn, vlu, point_name
    # deleting the initial row after finding the next column
    ndc = np.delete(ndc, rw, axis=0)
    ndc = np.delete(ndc, rw, axis=1)
    display(ndc)
    ndc.shape
    # the current column
    cl = lcn
    # current array
    # the slice at the end to remove the point column
    curr = ndc[:,cl][1:]

    # curr.

    # find the nonzero minimum of the current array
    minval = np.where( curr == np.min(curr[np.nonzero(curr)]) )
    lcn, vlu  = minval[0][0], curr[minval].tolist()[0]
    point_name = np.where( ndist[:,cl] == vlu)[0][0]-1
    print(cl, lcn, vlu, point_name)
    # appending the results of this stage to the results lists
    res_loc.append(point_name)
    res_val.append(vlu)
    # lcn, vlu, point_name
    # deleting the finished column
    ndc = np.delete(ndc, cl, axis=1)
    ndc = np.delete(ndc, cl, axis=0)
    
    return point_name

rw = 1
while ndc.shape[0]>2:
    rw = do_one_step(rw, ndc)
    
res_loc, res_val



1 9 4.123105625617661 10
9 7 10.0 9
9 0 6.082762530298219 1
0 0 1.0 0
0 0 1.0 1


IndexError: index 0 is out of bounds for axis 0 with size 0